CREATE SEQUENCE SAUDE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT01_SAUDE
    SET PS_ID = SAUDE_ID_SEQ.NEXTVAL;



CREATE SEQUENCE MEDICO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT02_MEDICO
    SET MD_ID = MEDICO_ID_SEQ.NEXTVAL;



CREATE SEQUENCE AGSAUDE_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT03_AGSAUDE
    SET AG_ID = AGSAUDE_ID_SEQ.NEXTVAL;



CREATE SEQUENCE FAMILIA_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT04_FAMILIA
    SET FM_ID = FAMILIA_ID_SEQ.NEXTVAL;



CREATE SEQUENCE MEMBRO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT05_MEMBRO
    SET MB_ID = MEMBRO_ID_SEQ.NEXTVAL;



CREATE SEQUENCE REGVACIN_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT06_REGVACIN
    SET RV_ID = REGVACIN_ID_SEQ.NEXTVAL;



CREATE SEQUENCE ESPECIALI_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT09_ESPECIALI
    SET ES_ID = ESPECIALI_ID_SEQ.NEXTVAL;



CREATE SEQUENCE SEXO_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    CACHE 20;
    
UPDATE HT10_SEXO
    SET SX_ID = SEXO_ID_SEQ.NEXTVAL;